### PR TITLE
Karaage 3.1.17 

### PR DESCRIPTION
**Pull request by shahaan**
Some New files are added as well. The buildKaraage playbook and vars/karaageVars has all the variable references I am using.

### CODE REVIEW

**Comment by l1ll1** [comment]
Hi Shahaan,
I though I had commented already, but apparently my comment got lost. A list of changes and questions follows:

1) could you please put the contents of vars/karaageVars.yml directly into the playbook buildKaraage3.x.yml. I don't really want playbooks in ansible_cluster_in_a_box, (i'd rather them in a specific repo)

2) in headNode.yml did you mean NFS instead of NSF?

3) in roles/easy-rsa-certificate/tasks/buildCert.yml could you please change 
delegate_to: "{{ hostvars[x509_ca_server]['ansible_fqdn'] }}"
back to
delegate_to: "{{ x509_ca_server }}"
or explain why you made this change. I don't believe your current one is correct

4) since your using roles/easy-rsa-common/tasks/installEasyRsaSource.yml could you please git rm roles/easy-rsa-common/tasks/installEasyRsa.yml

5) as part of installing roles/easy-rsa-common/tasks/installEasyRsaSource.yml do you need to install openssl? Its not distributed as part of easyRsa is it? are you testing these roles on clean never been used before VMs each time before submitting the pull request?

6) in roles/easy-rsa-common/tasks/yumList.yml you sysctl kernel.hostname={{ inventory_hostname }}
Rather than doing this as part of easy-rsa could you please do it as part of etcHosts role Could you please evaluate if its necessary on Debian family as well as RedHat family (you appear to only be doing it on RedHat family at the moment)

7) please git rm roles/karaage3.1.17/templates/.my.cnf.j2 and remove commented sections from roles/karaage3.1.17/tasks/mysql.yml

8) please don't template roles/karaage3.1.17/templates/settings.py.j2. Instead define lineinfile tasks to make edits to settings.py. Hopefully this will make upgrades to karaage where settings.py needs to change easier

9) in roles/ldapserver/tasks/main.yml you have
 - name: hash password
   command: /usr//sbin/slappasswd -h {SSHA} -s {{ ldapManagerPassword }}
   register: ldapManagerHash
note the extra / between usr and sbin. Could you remove this please

10) please git rm roles/karaage3.1.17/templates/client-ldap.conf.j2 and remove 
+ name: Templating ldap.conf
+ template: src=client-ldap.conf.j2 dest=/etc/ldap/ldap.conf owner=root group=root mode=0644
+ when: ansible_fqdn != "{% for host in groups['ldap-server'] %}{{ hostvars[host]['ansible_fqdn'] }}{% endfor %}"
from roles/karaage3.1.17/tasks/karaage.yml
Its not necessary to setup ldap.con on the karaage server (although it can be convenient)

11) please git rm roles/karaage3.1.17/templates/sqlsettings.sql.j2 (you don't use it anymore)

12) please git rm roles/karaage3.1.17/vars/main.yml. These vars need to be defined in a playbook or in a separate repo

13) please check that roles/ldapserver/templates/manager_ldif2.j2 works as you expect it to. You've changed an add to a replace and I don't think that will work on a clean ldap server install

14) please check the database name in roles/ldapserver/templates/tls_settings.ldif.j2. Should it be  {{dbname}} rather than olcDatabase={1}hdb

15) please git rm roles/nfs-client/vars/main.yml roles/nfs-server/defaults/main.yml. These should be in the playbook. You could git mv to a readme file if you like.

16) please check roles/nfs-server/tasks/mkFilesystem.yml. You didn't merge correctly.

17) please check roles/syncExports/tasks/addExports.yml. You didn't merge correctly.

18) roles/syncExports/vars/main.yml. As above. Please git rm and put in your playbook or move to a readme as an example.

19) please git rm vars/karaageVars.yml (see comment 1)

**Comment by shahaan** [comment]
Howdy Chris,

On Fri, Jul 3, 2015 at 12:34 PM, Chris Hines <notifications@github.com>
wrote:

> Hi Shahaan,
> I though I had commented already, but apparently my comment got lost. A
> list of changes and questions follows:
>
> 1) could you please put the contents of vars/karaageVars.yml directly into
> the playbook buildKaraage3.x.yml. I don't really want playbooks in
> ansible_cluster_in_a_box, (i'd rather them in a specific repo)
>
Done.

> *2) in headNode.yml did you mean NFS instead of NSF?*
>
*Supposed to be NFS but I made a mistake when creating the security group
as NSF :P, I don;t think that's crucial.. *

> 3) in roles/easy-rsa-certificate/tasks/buildCert.yml could you please
> change
> delegate_to: "{{ hostvars[x509_ca_server]['ansible_fqdn'] }}"
> back to
> delegate_to: "{{ x509_ca_server }}"
> or explain why you made this change. I don't believe your current one is
> correct
>
Done.


> 4) since your using roles/easy-rsa-common/tasks/installEasyRsaSource.yml
> could you please git rm roles/easy-rsa-common/tasks/installEasyRsa.yml
>
 Done.

> 5) as part of installing
> roles/easy-rsa-common/tasks/installEasyRsaSource.yml do you need to install
> openssl? Its not distributed as part of easyRsa is it? are you testing
> these roles on clean never been used before VMs each time before submitting
> the pull request?
>
Yes.

> *6) in roles/easy-rsa-common/tasks/*
> *yumList.yml you sysctl kernel.hostname={{ inventory_hostname }} Rather
> than doing this as part of easy-rsa could you please do it as part of
> etcHosts role Could you please evaluate if its necessary on Debian family
> as well as RedHat family (you appear to only be doing it on RedHat family
> at the moment)*
>
* I am not using etcHosts rule because it was breaking some of the stuff. I
can add Debian packages as well.*

> 7) please git rm roles/karaage3.1.17/templates/.my.cnf.j2 and remove
> commented sections from roles/karaage3.1.17/tasks/mysql.yml
>
Done. Thanks for pointing that out.

> *8) please don't template roles/karaage3.1.17/templates/**settings.py.j2.
> Instead define lineinfile tasks to make edits to settings.py. Hopefully
> this will make upgrades to karaage where settings.py needs to change easier*
>
*There is not harm in templating basic settings.py for things(lines) which
we know we have to  keep. We can discuss on this. *

> 9) in roles/ldapserver/tasks/main.yml you have
>
>    - name: hash password command: /usr//sbin/slappasswd -h {SSHA} -s {{
>    ldapManagerPassword }} register: ldapManagerHash note the extra / between
>    usr and sbin. Could you remove this please
>
> Done.

>
>
> *10) please git rm roles/karaage3.1.17/templates/**client-ldap.conf.j2
> and remove *
>
>    - *name: Templating ldap.conf*
>    - *template: src=client-ldap.conf.j2 dest=/etc/ldap/ldap.conf
>    owner=root group=root mode=0644*
>    - *when: ansible_fqdn != "{% for host in groups['ldap-server'] %}{{
>    hostvars[host]['ansible_fqdn'] }}{% endfor %}" from
>    roles/karaage3.1.17/tasks/**karaage.yml Its not necessary to setup
>    ldap.con on the karaage server (although it can be convenient)*
>
> *Chris, Karaage server is always the ldap-client machine (In case Ldap
server is the same machine, in order to access the Ldap through TLS this
setting is necessary), In fact I should be removing the "when" condition
altogether to apply this rule on the machine where Karaage is running
regardless if ldapserver is running there or not. Let me know, what you
think.*

>
>
> 11) please git rm roles/karaage3.1.17/templates/sqlsettings.sql.j2 (you
> don't use it anymore)
>
 Done.

> 12) please git rm roles/karaage3.1.17/vars/main.yml. These vars need to be
> defined in a playbook or in a separate repo
>
Done.

> *13) please check that roles/ldapserver/templates/**manager_ldif2.j2
> works as you expect it to. You've changed an add to a replace and I don't
> think that will work on a clean ldap server install*
>
*Replace works with the new ldapserver version. The problem comes when you
rerun playbooks. We can discuss this. *

> 14) please check the database name in
> roles/ldapserver/templates/tls_settings.ldif.j2. Should it be {{dbname}}
> rather than olcDatabase={1}hdb
>
 Correct, done.

> 15) please git rm roles/nfs-client/vars/main.yml
> roles/nfs-server/defaults/main.yml. These should be in the playbook. You
> could git mv to a readme file if you like.
>
Done.

> 16) please check roles/nfs-server/tasks/mkFilesystem.yml. You didn't merge
> correctly.
>
Done.

> 17) please check roles/syncExports/tasks/addExports.yml. You didn't merge
> correctly.
>
 Done.

> 18) roles/syncExports/vars/main.yml. As above. Please git rm and put in
> your playbook or move to a readme as an example.
>
Done .

> 19) please git rm vars/karaageVars.yml (see comment 1)
>
Done.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/monash-merc/ansible_cluster_in_a_box/pull/93#issuecomment-118214275>
> .
>

I will create a pull request once we are happy with the points I have
outlined for "to be discussed".

regards,

Shahaan

**Comment by l1ll1** [comment]
*Chris, Karaage server is always the ldap-client machine (In case Ldap
server is the same machine, in order to access the Ldap through TLS this
setting is necessary), In fact I should be removing the "when" condition
altogether to apply this rule on the machine where Karaage is running
regardless if ldapserver is running there or not. Let me know, what you
think.*


Sorry I wasn't more clear. Yes the karaage application is an ldap client. But the config file /etc/ldap.conf is not used by the karaage application, only by the ldapsearch application. My point was that since this is a config file for a completly different applcation it shouldn't be in the karaage role. If you tell me ldap.conf is used by karaage/django, fine, but I don't believe it is. All that info is replicated in other settings files.

* I am not using etcHosts rule because it was breaking some of the stuff. I
can add Debian packages as well.*

Its not really a package though. I just want you to tidy up and not do setting the host name in the karaage role. Do it in etcHosts, or create a new role so that only tasks relating to karaage are done in the karaage role. I'd like to figure out why etcHosts isn't working for you though. Is it because you don't have all hosts in the play yet? i.e. your not running on hosts: '*'?


*Replace works with the new ldapserver version. The problem comes when you
rerun playbooks. We can discuss this. *

There is supposed to be lots when statements so that it won't attempt to add the manager, if the slapd config already has a manager configured to prevent problems when rerunning. Are these failing for you? specifically

- name: initialise server manager
  shell:  ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/manager.ldif -D cn=config
  sudo: true
  when: managerConfigured|failed

should prevent problems.

**Comment by shahaan** [comment]
On Tue, Jul 7, 2015 at 12:19 AM, Chris Hines <notifications@github.com>
wrote:

>
>
>
>
>
> *Chris, Karaage server is always the ldap-client machine (In case Ldap
> server is the same machine, in order to access the Ldap through TLS this
> setting is necessary), In fact I should be removing the "when" condition
> altogether to apply this rule on the machine where Karaage is running
> regardless if ldapserver is running there or not. Let me know, what you
> think.*
>
> Sorry I wasn't more clear. Yes the karaage application is an ldap client.
> But the config file /etc/ldap.conf is not used by the karaage application,
> only by the ldapsearch application. My point was that since this is a
> config file for a completly different applcation it shouldn't be in the
> karaage role. If you tell me ldap.conf is used by karaage/django, fine, but
> I don't believe it is. All that info is replicated in other settings files.
>
You are right, that goes in the Karaage settings.py


>
>    - I am not using etcHosts rule because it was breaking some of the
>    stuff. I can add Debian packages as well.*
>
> Its not really a package though. I just want you to tidy up and not do
> setting the host name in the karaage role. Do it in etcHosts, or create a
> new role so that only tasks relating to karaage are done in the karaage
> role. I'd like to figure out why etcHosts isn't working for you though. Is
> it because you don't have all hosts in the play yet? i.e. your not running
> on hosts: '*'?
>
I need to look into the etcHosts script to identify the tweaks I need to do
at my end, and I just wanted to avoid that...

> *Replace works with the new ldapserver version. The problem comes when you
> rerun playbooks. We can discuss this. *
>
> There is supposed to be lots when statements so that it won't attempt to
> add the manager, if the slapd config already has a manager configured to
> prevent problems when rerunning. Are these failing for you? specifically
>
>    - name: initialise server manager shell: ldapmodify -Y EXTERNAL -H
>    ldapi:/// -f /tmp/manager.ldif -D cn=config sudo: true when:
>    managerConfigured|failed
>
> should prevent problems.
>
Hmmm... Let me check again, I remember putting that due to some problems. I
will revert it back after testing...

**Comment by shahaan** [comment]
I have updated the core as per the discussion above. I suggest a little bit of change in the makehosts.py file, where I allow null value for the domain variable.

**Pull request merged**
