### PR TITLE
(1) ssl.conf boken debian 8, removed; (2) fixed ldapserver https for …

### PR DESCRIPTION
**Pull request by CVL-GitHub**
(1) karaage 3 ssl.conf boken debian 8, removed it fro debian 8.

(2) fixed ldapserver configure for using https in centos 7.

### CODE REVIEW

**Comment by l1ll1** [comment]
Check the file roles/shibboleth-sp/tasks/shibbolethConfig.yml
There are a couple of places where you typed tarted instead of restarted

**Comment by l1ll1** [comment]
Also, general recomendation. Don't use git commit -a, use git add <file> and git commit. And before you do git add <file> do git status ; git diff <file> and make sure the diff looks good.

**Comment by CVL-GitHub** [comment]
Fixed typo

**Comment by shahaan** [comment]
Jupiter, 
  Please do a git pull, before making changes to the code. I have already removed tempting ssl.con in fact I am now simply editing the default-ssl and 000-default configuration files. My mistake that I did not do a git rm of these files. you could have saved all that effort...

regards,

Shahaan

**Pull request merged**
